version: "2"
services:
  profile_page:
    build: dg_frontend
    restart: always
    ports:
      - "3000:3000"
    links:
      - api
  api:
    build: api
    restart: always
    ports:
      - "9000:9000"
    links:
      - postgres_db
  postgres_db:
    build: db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: oisin
      POSTGRES_PASSWORD: oisin
    ports:
      - "8080:5432"
    restart: always
