version: "2"
services:
  dg_frontend:
    build: dg_frontend
    restart: always
    ports:
      - "3000:3000"
    links:
      - api
  api:
    build: api
    restart: always
    ports:
      - "9000:9000"
    links:
      - postgres_db
  postgres_db:
    build: db
    env_file:
      - db_auth.env
    ports:
      - "8080:5432"
    restart: always
